---
-
  name: 'Key request - ID'
  description: 'Obtain agent key with specific ID'
  test_case:
  -
    input: "id:001"
    log:
      - Requesting local addition for agent '001' from the agent key request.
      - '{"error":0,"data":{"id":"001","name":"wazuh_agent1","ip":"any","key":"675aaf366e6827ee7a77b2f7b4d89e603a21333c09afbb02c40191f199d7c911"}}'
-
  name: 'Key request - IP'
  description: 'Obtain agent key with specific IP'
  test_case:
  -
    input: "ip:10.10.10.10"
    log:
      - Requesting local addition for agent '002' from the agent key request.
      - '{"error":0,"data":{"id":"002","name":"wazuh_agent2","ip":"10.10.10.10","key":"675aaf366e6827ee7a77b2f7b4d89e603a21333c09afbb02c40191f199d7c912"}}'
# -
#   name: 'Error 1 Key request' # With a bad exec_path conf
#   description: 'Too few arguments passed to exec_path conf'
#   test_case:
#   -
#     input: "id:003"
#     output: '{"error": 1, "message": "Too few arguments"}'
#     log:
#       - Duplicate name. Removing old agent 'agent_recently_added_dup_name' (id '001').

# -
#   name: 'Error 2 Key request' # Can obtain a script failure?
#   description: 'Script error'
#   test_case:
#   -
#     input: "id:004"
#     output: '{"error": 2, "message": "ERROR"}'
#     log:
#       - Duplicate name. Removing old agent 'agent_recently_added_dup_name' (id '001').

# -
#   name: 'Error 3 Key request' # Is possible get bad arguments?
#   description: 'Bad arguments given to the script'
#   test_case:
#   -
#     input: "id:005"
#     output: '{"error": 3, "message": "Bad arguments given"}'
#     log:
#       - Duplicate name. Removing old agent 'agent_recently_added_dup_name' (id '001').

-
  name: 'Error 4 Key request'
  description: 'The script does not have any key for the agent ID/IP'
  test_case:
  -
    input: "id:004"
    log:
      - '{"error": 4, "message": "No agent key found"}'
      - "Could not get a key from ID 004. Error: 'No agent key found'"

-
  name: 'Error 5 Key request'
  description: 'The script has more than one entry for the agent ID.'
  test_case:
  -
    input: "id:007"
    log:
      - '{"error": 5, "message": "Found more than one match for required id"}'
      - "Could not get a key from ID 007. Error: 'Found more than one match for required id'"
